version: "3"

services:
  db:
    image: postgres:9.6
    volumes:
      - database_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    expose:
       - "5432"
    env_file:
      - .env

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/trading-bot
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    links:
      - db
    depends_on:
      - db

  celery:
    build: .
    command: >
      sh -c "./bin/wait-for-it.sh db:5432 && ./bin/wait-for-it.sh redis:6379
      -- celery -A server.config worker --concurrency 1 --loglevel=info
      --without-heartbeat --without-gossip --without-mingle"
    volumes:
      - .:/trading-bot
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery-beat:
    build: .
    command: >
      sh -c "./bin/wait-for-it.sh db:5432 && ./bin/wait-for-it.sh redis:6379
      -- celery -A server.config beat -l info -S django"
    volumes:
      - .:/trading-bot
    env_file:
      - .env
    links:
      - db
      - redis
      - celery
    depends_on:
      - db
      - redis
      - celery

volumes:
  database_data:
