version: "3"

services:
  db:
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tradingbot
      - POSTGRES_USER=tradingbot
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: sh -c "celery -A server.config worker -l info"
    volumes:
      - .:/trading-bot
    depends_on:
      - redis
    env_file:
      - .env

  celery-beat:
    build: .
    command: sh -c "celery -A server.config beat -l info"
    volumes:
      - .:/trading-bot
    env_file:
      - .env
    depends_on:
      - redis
      - celery

volumes:
  postgres_data:
