version: "3"

services:
  postgres:
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: sh -c "celery -A api.config worker -l info"
    volumes:
      - .:/trading-bot
    depends_on:
      - redis
    env_file:
      - .env

  celery-beat:
    build: .
    command: sh -c "celery -A api.config beat -l info"
    volumes:
      - .:/trading-bot
    env_file:
      - .env
    depends_on:
      - redis
      - celery

volumes:
  postgres_data:
